[tool.black]
line-length = 79
target-version = ["py36", "py37", "py38"]

[tool.poetry]
name = "pyrencode"
version = "0.1.3"
description = "A pure python rencoder"
authors = ["spapanik <spapanik21@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
pytest = "^4.4"
ipython = "^7.2"
ipdb = "^0.12"
